name: 'Pull Request Action'
description: 'A GitHub action to open a pull request on new/update of branch'
author: 'vsoch'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'activity'  
  color: 'yellow'
